### ISSUE TITLE
Itens de pedido

### ISSUE THREAD

**Issue by euperinotti** [anaclaraberga/API-WEB-INVENTORY#4]
## Funcionalidades
- [x] Adição de Itens de Pedido: Associar produtos a um pedido.
- [x] Remoção de Itens de Pedido: Excluir produtos de um pedido.
- [x] Listagem de Itens de Pedido: Exibir os itens relacionados a um pedido específico.

## Requisitos funcionais
- CRUD de itens de pedido (associados a produtos e pedidos).
- Validação: quantidade deve ser maior que 0 e precoUnitario deve ser positivo.

## Regras de negócio
- quantidade deve ser maior que 0.
- precoUnitario deve ser maior que 0.

## Entidade
| Campo        | Tipo   | Descrição                                      |
|--------------|--------|------------------------------------------------|
| id           | number | Chave primária                                 |
| pedidoId     | number | Chave estrangeira para a tabela Pedido         |
| produtoId    | number | Chave estrangeira para a tabela Produto        |
| quantidade   | number | Quantidade do produto no pedido                |
| precoUnitario| number | Preço unitário do produto no pedido            |

**Comment by anaclaraberga** [comment]
Done, bro.
